import type { PlasmoConfig } from "plasmo"

export const config: PlasmoConfig = {
  manifest: {
    manifest_version: 3,
    name: "SnipDM",
    version: "1.0.0",
    description: "Insert DM snippets into any text field from your SnipDM workspace.",
    permissions: ["storage", "activeTab", "scripting"],
    host_permissions: ["<all_urls>"],
    action: {
      default_title: "SnipDM"
    },
    // Icons are generated by Plasmo from assets/icon.png (see docs.plasmo.com/framework/icon)
    commands: {
      "open-snippet-picker": {
        suggested_key: {
          default: "Ctrl+Shift+Space",
          mac: "Command+Shift+Space"
        },
        description: "Open the SnipDM snippet picker"
      }
    }
  }
}
